### ISSUE TITLE
the bot isn't responding to commands and reports this error in command prompt 

### ISSUE THREAD

**Issue by CoolRaven** [ecatherine13/Ultimate-Assistant#41]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 975, in process_commands
    ctx = await self.get_context(message)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 886, in get_context
    prefix = await self.get_prefix(message)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 831, in get_prefix
    ret = await discord.utils.maybe_coroutine(prefix, self, message)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\utils.py", line 341, in maybe_coroutine
    value = f(*args, **kwargs)
  File "C:\Users\User\Downloads\Ultimate-Assistant-master\Ultimate-Assistant-master\main.py", line 19, in prefix
    cs.execute(f"SELECT Prefix FROM GuildData WHERE GuildID == {guild_id} LIMIT 1")
sqlite3.OperationalError: no such column: Prefix

**Comment by ecatherine13** [comment]
This code has not been updated in two years and it is likely that many things are deprecated, or otherwise no longer supported by discord. Continue with it at your own risk. I'm assuming you're testing in a discord server.

This error in particular seems to be an issue with the sqlite3 database. Make sure that there is a column titled Prefix in the connected database. Otherwise, make sure that the server ID in question is present in the GuildData table.
